version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    environment:
      RABBITMQ_DEFAULT_USER: secretusername
      RABBITMQ_DEFAULT_PASS: secretpassword123
      RABBITMQ_DEFAULT_VHOST: dev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    restart: always

  cockroachdb-1:
    image: cockroachdb/cockroach:v22.1.0
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    volumes:
      - "./cockroachdb_data/cockroachdb-1:/cockroach/cockroach-data"
    ports:
      - "26257:26257"
      - "8080:8080"
    restart: always

  cockroachdb-2:
    image: cockroachdb/cockroach:v22.1.0
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    volumes:
      - "./cockroachdb_data/cockroachdb-2:/cockroach/cockroach-data"
    restart: always

  cockroachdb-3:
    image: cockroachdb/cockroach:v22.1.0
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    volumes:
      - "./cockroachdb_data/cockroachdb-3:/cockroach/cockroach-data"
    restart: always
