version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    restart: always

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    restart: always
