version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    environment:
      RABBITMQ_DEFAULT_USER: secretusername
      RABBITMQ_DEFAULT_PASS: secretpassword123
      RABBITMQ_DEFAULT_VHOST: dev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    restart: always

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=secretusername
      - POSTGRES_DB=gompq
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    restart: always
